# Generated by Django 3.1.1 on 2021-01-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
