# Generated by Django 3.1.1 on 2021-01-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210120_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name_plural': 'Description'},
        ),
    ]
