# Generated by Django 3.1.1 on 2021-01-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210128_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_key', models.TextField()),
                ('content_extra', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'Index Description',
            },
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name_plural': ' About page'},
        ),
    ]
