# Generated by Django 3.1.1 on 2021-01-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210128_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='meddia/carousel/')),
            ],
            options={
                'verbose_name_plural': 'Carousel',
            },
        ),
    ]
