# Generated by Django 3.1.6 on 2021-02-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name_plural': ' About page contents'},
        ),
        migrations.AlterModelOptions(
            name='indexdescription',
            options={'verbose_name_plural': 'Home page contents'},
        ),
    ]
