# Generated by Django 3.2.4 on 2021-06-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210223_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
